package libvalidator

import (
	libparser "github.com/tomefile/lib-parser"
)

// Validated version of [libparser.StringNode]
type ValidStringNode struct {
	Original string

	// Holds segments generated by [libparser.StringFormatter]
	Segments []libparser.Segment
}

func (node *ValidStringNode) Node() string {
	return node.Original
}
